-- 为products表添加图片字段
ALTER TABLE products ADD COLUMN image_url VARCHAR(500) DEFAULT NULL;
ALTER TABLE products ADD COLUMN image_alt VARCHAR(255) DEFAULT NULL;
ALTER TABLE products ADD COLUMN detailed_description TEXT DEFAULT NULL;

-- 创建商品图片表，支持多张图片
CREATE TABLE product_images (
  id INT PRIMARY KEY AUTO_INCREMENT,
  product_id INT NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  image_alt VARCHAR(255) DEFAULT NULL,
  is_primary BOOLEAN DEFAULT FALSE,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  INDEX idx_product_id (product_id),
  INDEX idx_is_primary (is_primary)
);

-- 添加更多商品详情字段
ALTER TABLE products ADD COLUMN specifications JSON DEFAULT NULL;
ALTER TABLE products ADD COLUMN brand VARCHAR(100) DEFAULT NULL;
ALTER TABLE products ADD COLUMN model VARCHAR(100) DEFAULT NULL;
ALTER TABLE products ADD COLUMN weight DECIMAL(10,3) DEFAULT NULL;
ALTER TABLE products ADD COLUMN dimensions VARCHAR(100) DEFAULT NULL;
ALTER TABLE products ADD COLUMN color VARCHAR(50) DEFAULT NULL;
ALTER TABLE products ADD COLUMN material VARCHAR(100) DEFAULT NULL;